#!/usr/bin/env python3
"""Inspect connected RealSense cameras and (re)generate cams.env.

The relay auto-discovers cameras at startup (see relay/cameras.py), so this
script is for humans: confirm what the bus looks like, and write a cams.env
you can `source` for a shell that needs the CAM_* vars (e.g. the recorder).

    python tools/gen_cams_env.py            # print discovery table, no writes
    python tools/gen_cams_env.py --write    # regenerate ./cams.env
    python tools/gen_cams_env.py --write -o /path/cams.env

Exit status is non-zero if any mapped role is missing from the bus, so it is
safe to gate a launch script on it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow running straight from a source checkout without installing.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from vr_teleop_kit.relay.cameras import ROLES, discover  # noqa: E402

HEADER = (
    "# RealSense color streams, pinned by serial (stable across reboot/replug).\n"
    "# GENERATED by tools/gen_cams_env.py — do not hand-edit; update the\n"
    "# serial->role map in src/vr_teleop_kit/relay/cameras.py instead.\n"
    "# Usage:  source cams.env   then run vr-teleop-relay\n"
)


def render(result) -> str:
    lines = [HEADER]
    for role, (env_var, _cam_id, label) in ROLES.items():
        found = result.matched.get(role)
        if found:
            lines.append(f"export {env_var}={found.device}  # {label} (serial {found.serial})")
        else:
            lines.append(f"# {env_var} unset  # {label}: no matching camera on the bus")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write the env file instead of only printing")
    ap.add_argument("-o", "--output", default="cams.env", help="output path for --write (default: ./cams.env)")
    args = ap.parse_args()

    result = discover()

    print("role        serial          device")
    print("----        ------          ------")
    for role, (_env, _cam_id, label) in ROLES.items():
        found = result.matched.get(role)
        if found:
            print(f"{role:<11} {found.serial:<15} {found.device}")
        else:
            print(f"{role:<11} {'-':<15} (not found)")

    for serial in result.unmapped_serials:
        print(f"\nWARNING: serial {serial} is connected but unmapped — add it to "
              "SERIAL_TO_ROLE in src/vr_teleop_kit/relay/cameras.py", file=sys.stderr)

    if args.write:
        out = Path(args.output)
        out.write_text(render(result))
        print(f"\nwrote {out} ({len(result.matched)}/{len(ROLES)} roles resolved)")

    return 1 if result.missing_roles else 0


if __name__ == "__main__":
    raise SystemExit(main())
